# Use uma imagem base Python oficial.
FROM python:3.11-slim

# Defina o diretório de trabalho.
WORKDIR /app

# Copie e instale as dependências.
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copie seu script Python.
COPY nyt_producer.py .

# Comando para executar o script.
CMD ["python", "nyt_producer.py"]